import { Employee } from './types';

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    firstName: 'Barbara',
    lastName: 'Kowalska',
    fullName: 'Barbara Kowalska',
    persona: 'Doświadczony menedżer',
    description: 'Ceni szczegóły, kontekst i formalny ton. Preferuje pełną informację przed podjęciem decyzji.',
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    preferredVariant: 'detailed',
    generation: 'Boomer',
  },
  {
    id: 'emp-2',
    firstName: 'Krzysztof',
    lastName: 'Nowak',
    fullName: 'Krzysztof Nowak',
    persona: 'Pragmatyczny dyrektor',
    description: 'Ceni zwięzłość i praktyczne podejście. Nie lubi zbędnych ozdobników - prosto do rzeczy.',
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
    preferredVariant: 'short',
    generation: 'Gen X',
  },
  {
    id: 'emp-3',
    firstName: 'Anna',
    lastName: 'Wiśniewska',
    fullName: 'Anna Wiśniewska',
    persona: 'Współpracująca liderka projektu',
    description: 'Lubi jasną strukturę i wyraźne sekcje. Preferuje organizację informacji z nagłówkami.',
    avatarUrl: 'https://i.pravatar.cc/150?img=32',
    preferredVariant: 'subsections',
    generation: 'Millennial',
  },
  {
    id: 'emp-4',
    firstName: 'Michał',
    lastName: 'Zieliński',
    fullName: 'Michał Zieliński',
    persona: 'Młody analityk',
    description: 'Chce konkretów - liczby, fakty, dane. Lubi wiedzieć "ile", "kiedy", "jak dużo".',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    preferredVariant: 'data-driven',
    generation: 'Gen Z',
  },
  {
    id: 'emp-5',
    firstName: 'Ewa',
    lastName: 'Dąbrowska',
    fullName: 'Ewa Dąbrowska',
    persona: 'Zajęta specjalistka HR',
    description: 'Potrzebuje szybko znać najważniejsze - TL;DR na początku, szczegóły jeśli potrzeba.',
    avatarUrl: 'https://i.pravatar.cc/150?img=38',
    preferredVariant: 'tldr-first',
    generation: 'Millennial',
  },
  {
    id: 'emp-6',
    firstName: 'Tomasz',
    lastName: 'Lewandowski',
    fullName: 'Tomasz Lewandowski',
    persona: 'Wykonawczy koordynator',
    description: 'Chce wiedzieć co ma zrobić, kiedy i jak. Skupia się na akcjach i deadlinach.',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    preferredVariant: 'action-oriented',
    generation: 'Gen X',
  },
  {
    id: 'emp-7',
    firstName: 'Karolina',
    lastName: 'Wójcik',
    fullName: 'Karolina Wójcik',
    persona: 'Kreatywna marketerka',
    description: 'Lubi wizualną komunikację - emoji, ikony, kolory. To pomaga jej zapamiętać informacje.',
    avatarUrl: 'https://i.pravatar.cc/150?img=45',
    preferredVariant: 'visual',
    generation: 'Gen Z',
  },
  {
    id: 'emp-8',
    firstName: 'Piotr',
    lastName: 'Kamiński',
    fullName: 'Piotr Kamiński',
    persona: 'Skanująca informacje',
    description: 'Nie ma czasu na długie czytanie - bullet points pozwalają szybko przeskanować treść.',
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
    preferredVariant: 'bullets',
    generation: 'Millennial',
  },
  {
    id: 'emp-9',
    firstName: 'Maria',
    lastName: 'Jankowska',
    fullName: 'Maria Jankowska',
    persona: 'Tradycyjna dyrektorka',
    description: 'Ceni formalny, profesjonalny ton. Oczekuje korporacyjnego standardu komunikacji.',
    avatarUrl: 'https://i.pravatar.cc/150?img=48',
    preferredVariant: 'formal',
    generation: 'Boomer',
  },
  {
    id: 'emp-10',
    firstName: 'Jakub',
    lastName: 'Mazur',
    fullName: 'Jakub Mazur',
    persona: 'Przyjazny junior developer',
    description: 'Preferuje luźny, przyjacielski ton. Oficjalna komunikacja go stresuje.',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    preferredVariant: 'casual',
    generation: 'Gen Z',
  },
  {
    id: 'emp-11',
    firstName: 'Magdalena',
    lastName: 'Krawczyk',
    fullName: 'Magdalena Krawczyk',
    persona: 'Pytająca account manager',
    description: 'Myśli pytaniami. Format FAQ pozwala jej lepiej zrozumieć temat.',
    avatarUrl: 'https://i.pravatar.cc/150?img=43',
    preferredVariant: 'faq',
    generation: 'Millennial',
  },
  {
    id: 'emp-12',
    firstName: 'Andrzej',
    lastName: 'Piotrowski',
    fullName: 'Andrzej Piotrowski',
    persona: 'Standardowy pracownik',
    description: 'Zadowoli go zwykła, wyważona komunikacja bez szczególnych preferencji.',
    avatarUrl: 'https://i.pravatar.cc/150?img=16',
    preferredVariant: 'base',
    generation: 'Gen X',
  },
  {
    id: 'emp-13',
    firstName: 'John',
    lastName: 'Johnson',
    fullName: 'John Johnson',
    persona: 'English-speaking expat',
    description: 'Jedyny anglojęzyczny pracownik. Wszystkie komunikaty muszą być przetłumaczone na angielski.',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    preferredVariant: 'english',
    generation: 'Millennial',
  },
  {
    id: 'emp-14',
    firstName: 'Dziwny',
    lastName: 'Mariusz',
    fullName: 'Dziwny Mariusz',
    persona: 'Miłośnik staropolszczyzny',
    description: 'Oczekuje komunikatów w imitacji staropolszczyzny, zawsze zaczynających się od "Mocium Panie,".',
    avatarUrl: 'https://i.pravatar.cc/150?img=52',
    preferredVariant: 'staropolski',
    generation: 'Gen X',
  },
  {
    id: 'emp-15',
    firstName: 'Luźna',
    lastName: 'Gosia',
    fullName: 'Luźna Gosia',
    persona: 'Super casual Gen Z',
    description: 'Komunikacja musi być mega luźna, dużo slangu, emotek, skrótów i memów. Przesadnie casualowo.',
    avatarUrl: 'https://i.pravatar.cc/150?img=44',
    preferredVariant: 'super-casual',
    generation: 'Gen Z',
  },
];

export function getEmployeeById(id: string): Employee | undefined {
  return EMPLOYEES.find(emp => emp.id === id);
}

export function getEmployeesByVariant(variant: string): Employee[] {
  return EMPLOYEES.filter(emp => emp.preferredVariant === variant);
}
